source("./R/internals.R")
source("./R/convert_length_to_mass.R")
source("./R/wrap_dates.R")
source("./R/sf_prod.sample.R")
source("./R/prep_boots.R")
source("./R/calc_production.R")
source("./R/calc_prod_sf.R")
source("./R/plot_cohorts.R")
source("./R/my_boot.comp.R")
source("./R/pb_prod.sample.R")
source("./R/calc_prod_pb.R")

# devtools::install_github("jimjunker1/secpRod")
library(junkR)
library(tidyverse)
library(stagePop)
library(formula.tools)
library(mixtools)
library(brms)
library(rstan)
rstan::rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
library(tictoc)
